name: Test dependabot updates

on:
  push:
    tags: ['v*']

jobs:
  build:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      # this is simply an outdated version
      - uses: docker/setup-buildx-action@2e941f2defb78a11da0f277a3a76fb347dfd084b # v1.4.0
      # this is also an outdated version, but within the same major
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      # this is an outdated version and the version comment behind it is incorrect (the SHA is from v3.2.4)
      - uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920 # v3.4.5
