name: Test dependabot updates

on:
  push:
    tags: ['v*']

jobs:
  build:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      # this is simply an outdated version
      - uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
      # this is also an outdated version, but within the same major
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      # this is an outdated version and the version comment behind it is incorrect (the SHA is from v3.2.4)
      - uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.4.5
