name: Test dependabot updates

on:
  push:
    tags: ['v*']

jobs:
  build:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      # this is simply an outdated version
      - uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2.10.0
      # this is also an outdated version, but within the same major
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      # this is an outdated version and the version comment behind it is incorrect (the SHA is from v3.2.4)
      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.4.5
